### ISSUE TITLE
Descargar documento

### ISSUE THREAD

**Issue by evalbors** [CodersFactoria2020/Alumni#98]
Los archivos se suben y se almacenan en Storage:
$document = $upload->store('public/storage')

Pero al intentar la descarga me da error:
ErrorException: Trying to get property 'title' of non-object
return Storage::download($prueba->title, $prueba->document, $headers);

**Comment by evalbors** [comment]
Gracias!!

**Comment by EllaQuimica** [comment]
Hola, @evalbors podrias indicar en que commit o PR se resolvió este issue ?
